### ISSUE TITLE
Localizing text

### ISSUE THREAD

**Issue by Keony1** [TimboKZ/Chonky#15]
Hello guys!

I want to know if there is a way to change the default texts inside the components to another text.

Like "Nothing to show" when doesnt have anything in array of files to "Nada para mostrar"

Thank you!

**Comment by TimboKZ** [comment]
There isn't a built-in feature for customising text like that.

You have 2 options:
1. (Recommended) Override the text using CSS.
    ```css
    /* !!! This is just to get you started, you might need to customise CSS further  */

    .chonky-file-list-notification-empty .chonky-file-list-notification-content {
        font-size: 0;
    }

    .chonky-file-list-notification-empty .chonky-file-list-notification-content:after {
        content: 'Nada para mostrar';
        font-size: 16px;
    }
    ```
2. Clone Chonky source code and replace the text in the source.
