### ISSUE TITLE
[thumbnails] change background-size default value 

### ISSUE THREAD

**Issue by axel7083** [TimboKZ/Chonky#195]
The `chonky-fileThumbnail` class has the css value `background-size` set to `contain`, in some case we might want to have this value set to `cover` to take the full space available.

However, setting the following css 
```css
.chonky-fileThumbnail {
    background-size: cover;
}
```

Does not seems to work even, when importing after the chunky css.

**Comment by axel7083** [comment]
The current work around is to use the following css synthax:

```css
.chonky-fileThumbnail {
    background-size: cover !important;
}
```
