### ISSUE TITLE
How to hide search

### ISSUE THREAD

**Issue by burakozturk16** [TimboKZ/Chonky#74]

**Comment by niikkiin** [comment]
Hi @burakozturk16 maybe you can try to hide it using css, something like this worked for me.
``` css
.MuiFormControl-root.MuiTextField-root.chonky-searchFieldContainer {
    display: none;
}
```
or
``` css
.chonky-searchFieldContainer {
    display: none;
}
```
